# Étape 1 : Construction de l'application Angular
FROM node:14 AS build
WORKDIR /app

# Copier uniquement les fichiers nécessaires pour installer les dépendances
COPY package.json package-lock.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source dans l'image
COPY . .

# Construire l'application Angular
RUN npm run build -- --configuration=docker


# Étape 2 : Serveur NGINX pour héberger l'application
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

# Supprimer les fichiers par défaut NGINX
RUN rm -rf ./*

# Copier les fichiers Angular générés depuis l'étape précédente
COPY --from=build /app/dist/clientFormation .

# Copier le fichier de configuration NGINX personnalisé
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exposer le port 80
EXPOSE 80

# Commande par défaut pour démarrer
CMD ["nginx", "-g", "daemon off;"]
