version: '3.8'

services:
  backend:
    image: spring-boot-one-to-many:1.1-SNAPSHOT
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3308/formation
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      JAVA_OPTS: -Xmx512m
    depends_on:
      - mysql

  frontend:
    image: angular-frontend:latest
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "4202:80"

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3308:3306"
