
services:
  backend:
    image: spring-boot-one-to-many:1.1-SNAPSHOT
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/FORMATION?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JAVA_OPTS: -Xmx512m
    depends_on:
      - mysql

  frontend:
    image: angular-frontend:latest
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "4202:80"

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FORMATION
    ports:
      - "3310:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8085:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

