

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FORMATION
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - app-network
  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter
    environment:
      DATA_SOURCE_NAME: root:root@tcp(mysql:3306)/  # Assurez-vous que cet utilisateur existe dans MySQL
    volumes:
      - ./.my.cnf:/etc/.my.cnf  # Montez le fichier .my.cnf dans /etc/.my.cnf
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "9104:9104"  # Exposez le port pour accéder aux métriques
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql" ]  # Vérifie si MySQL répond correctement
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s


  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8085:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
  backend:
    image: spring-boot-one-to-many:1.1-SNAPSHOT
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "9095:9095"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/FORMATION?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&connectTimeout=5000&socketTimeout=5000
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: dev
      JAVA_OPTS: -Xmx512m
    depends_on:
      mysql:
        condition: service_healthy
      phpmyadmin:
        condition: service_started
    networks:
      - app-network

  frontend:
    image: angular-frontend:latest
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "4202:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

