# Étape 1 : Base image avec JDK 17 et Alpine Linux
FROM openjdk:17-jdk-alpine

# Étape 2 : Définir l'argument pour le fichier JAR
ARG JAR_FILE=target/spring-boot-one-to-many-1.1.0-SNAPSHOT.jar

# Étape 3 : Copier le fichier JAR dans l'image Docker
COPY ${JAR_FILE} /app.jar

# Étape 4 : Exposer le port de l'application
EXPOSE 9095

# Étape 5 : Commande pour exécuter l'application
ENTRYPOINT ["java","-jar","/app.jar"]
